BOARD_TAG   = nano
BOARD_SUB   = atmega328
AVRDUDE      = /usr/local/bin/avrdude
AVRDUDE_OPTS = -v
USER_LIB_PATH = ./libraries
ARDUINO_LIBS = Wire AccelStepper Servo
include /usr/local/opt/arduino-mk/Arduino.mk
